blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: https://adrianmejias.com
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
  - name: Documentation issue
    url: https://github.com/adrianmejias/veil/issues
    about: For documentation issues, open a pull request at the adrianmejias/veil repository
